on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  backend-frontend:
    name: Create backend and frontend releases
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: seg911
          password: edc0b48f-a58e-4715-ba51-98964fc07f3c

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: seg911/rubysocial:${{ steps.get_version.outputs.VERSION }}
          build-args: |
            RAILS_KEY=121f8616eee1d254eaac5b7d2ef6c179
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}